### ISSUE TITLE
[BUG] TotalScore should be based on current `SUBMIT`

### ISSUE THREAD

**Issue by awkonecki** [javadude97/SportsQuiz#10]
https://github.com/javadude97/SportsQuiz/blob/fd97319f7037f8de02425202d0cce3a3759edbc4/app/src/main/java/com/example/android/sportsquiz/MainActivity.java#L122-L128

`Line 122` should not have `+=` it should be `=` only.  This will prevent using the previous score for a new submit.

**Comment by awkonecki** [comment]
https://github.com/javadude97/SportsQuiz/blob/fd97319f7037f8de02425202d0cce3a3759edbc4/app/src/main/java/com/example/android/sportsquiz/MainActivity.java#L132-L135

Or you can move the `totalScore = 0;` line to be before call to `calculateTotalScore()`

**Comment by javadude97** [comment]
Thanks Andrew.
