### ISSUE TITLE
[BUG] Is Checked

### ISSUE THREAD

**Issue by awkonecki** [javadude97/SportsQuiz#9]
Maybe they want you to only support a single checkbox.  Thus you if on checking every box would not be necessary.

But I think your `CheckBox.setChecked(false);` should not exist and might by what the reviewer is complaining about.  

Upon submission, you might want o clear all the checkboxes and any user input.

```java
private int computeQuestion1Score() {
        CheckBox bearsCheckbox = (CheckBox) findViewById(R.id.chicago_bears_checkbox);
        boolean countsBears = bearsCheckbox.isChecked();
        CheckBox packersCheckbox = (CheckBox) findViewById(R.id.greenbay_packers_checkbox);
        boolean countsPackers = packersCheckbox.isChecked();
        CheckBox giantsCheckbox = (CheckBox) findViewById(R.id.newyork_giants_checkbox);
        boolean countsGiants = giantsCheckbox.isChecked();
        CheckBox redskinsCheckbox = (CheckBox) findViewById(R.id.washington_redskins_checkbox);
        boolean countsRedskins = redskinsCheckbox.isChecked();
        CheckBox allaboveCheckbox = (CheckBox) findViewById(R.id.all_above_checkbox);
        boolean countsAllabove = allaboveCheckbox.isChecked();


        /**If all four choices are NOT chosen then no points are assigned*/
        if ((countsBears && countsPackers && countsGiants && countsRedskins) || (countsAllabove))
        { scoreCounter +=1;

        } else {
            CheckBox.setChecked(false);
            toastMessage = " Incorrect! Please try again. ";
            getToast();
        }
        return scoreCounter;
    }
```

**Comment by awkonecki** [comment]
Remove 
>
https://github.com/javadude97/SportsQuiz/blob/ce765c60f6658db4a2f3ace2de0d8e25f887f6d6/app/src/main/java/com/example/android/sportsquiz/MainActivity.java#L44

**Comment by awkonecki** [comment]
Remove 
>
https://github.com/javadude97/SportsQuiz/blob/ce765c60f6658db4a2f3ace2de0d8e25f887f6d6/app/src/main/java/com/example/android/sportsquiz/MainActivity.java#L64

**Comment by awkonecki** [comment]
Remove
>
https://github.com/javadude97/SportsQuiz/blob/ce765c60f6658db4a2f3ace2de0d8e25f887f6d6/app/src/main/java/com/example/android/sportsquiz/MainActivity.java#L83

**Comment by javadude97** [comment]
Rewrote this entire method. Thanks for the tip.
